### ISSUE TITLE
Issue with built docs examples

### ISSUE THREAD

**Issue by Lewiscowles1986** [mroderick/plete-docs#7]
There is every chance this is a windows-specific bug as I tested this in Windows 10 during playing a game.

### Node version
v12.14.0

### NPM version
6.13.4

### Error (browser console)

> (index):87 GET http://localhost:8080/.netlify/functions/countries?query=england 404 (Not Found)
> filterCountries @ (index):87
> filter @ plete.js:209
> suggest @ plete.js:341
> (anonymous) @ plete.js:41
> setTimeout (async)
> (anonymous) @ plete.js:38

this triggers 

> plete.js:350 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

I'm fairly certain this is benign, as the intersection of users could be builds on windows, but it stops the autocomplete functioning

### data 

HAR attached
[plete-docs.zip](https://github.com/mroderick/plete-docs/files/4175565/plete-docs.zip)

Directory snapshot
[plete-docs.zip](https://github.com/mroderick/plete-docs/files/4175567/plete-docs.zip)

<details>
<summary>CLI commands run</summary>

```
lewis@LAPTOP-DCH0M5G9 MINGW64 /
$ cd ~/projects

lewis@LAPTOP-DCH0M5G9 MINGW64 ~/projects
$ git clone https://github.com/mroderick/plete-docs
Cloning into 'plete-docs'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 116 (delta 60), reRecueiving objects:  sed5 917 (del%t (6a 0/116)                                                                                                                    49), pack-reused 0
Receiving objects: 100% (116/116), 73.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (60/60), done.
Checking connectivity... done.

lewis@LAPTOP-DCH0M5G9 MINGW64 ~/projects
$ cd plete-docs/

lewis@LAPTOP-DCH0M5G9 MINGW64 ~/projects/plete-docs (master)
$ npm ci

> core-js@2.6.11 postinstall C:\Users\lewis\projects\plete-docs\node_modules\cor                                                                                                                   e-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfill                                                                                                                   ing JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Colle                                                                                                                   ctive or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a goo                                                                                                                   d job -)


> fsevents@1.2.11 install C:\Users\lewis\projects\plete-docs\node_modules\fseven                                                                                                                   ts
> node-gyp rebuild


C:\Users\lewis\projects\plete-docs\node_modules\fsevents>if not defined npm_conf                                                                                                                   ig_node_gyp (node "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\                                                                                                                   node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gy                                                                                                                   p.js" rebuild )  else (node "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_mo                                                                                                                   dules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2034, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1791, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1744, in _DictsToFolders
    for folder, contents in bucket.items():
AttributeError: 'MSVSProject' object has no attribute 'items'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\lewis\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lewis\\AppData\\Roaming\\nvm\\v12.14.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lewis\projects\plete-docs\node_modules\fsevents
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

> ejs@2.7.4 postinstall C:\Users\lewis\projects\plete-docs\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

added 474 packages in 33.372s

lewis@LAPTOP-DCH0M5G9 MINGW64 ~/projects/plete-docs (master)
$ npm start

> plete-docs@1.0.0 start C:\Users\lewis\projects\plete-docs
> eleventy --serve

Writing _site/README/index.html from ./README.md.
Writing _site/index.html from ./index.md.
Wrote 2 files in 0.40 seconds (v0.10.0)
Watching…
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:8080
    External: http://192.168.56.1:8080
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Serving files from: _site


lewis@LAPTOP-DCH0M5G9 MINGW64 ~/projects/plete-docs (master)
$ node --version
v12.14.0
n
lewis@LAPTOP-DCH0M5G9 MINGW64 ~/projects/plete-docs (master)
$ npm --version
6.13.4

lewis@LAPTOP-DCH0M5G9 MINGW64 ~/projects/plete-docs (master)
$
```

</details>

**Comment by Lewiscowles1986** [comment]
After checking this out on mac, it seems it's a compound issue. First `.netlify` is not setup on my system and does not resolve to the countries list.

Secondly response.ok is not checked, so the aborted / blank response (I've not checked which, but it's not JSON) triggers an error.

Given that the internet is full of copy-paste. I think if #10 is acceptable, then the only remaining part to this issue would be working out what to do about `.netlify` (which I think points at the countries list)
